### ISSUE TITLE
矩阵维度错误

### ISSUE THREAD

**Issue by li17855320680** [ridgerchu/SNN_Attention_VGG#2]
作者你好，我直接安装并运行了CIFAR10_VGG.py文件，但运行出来报了矩阵的错误，请作者帮忙看看，是否是源码存在问题，万分感谢！
![image](https://github.com/ridgerchu/SNN_Attention_VGG/assets/101408583/486e26b8-da69-45cb-8768-0ce0455276f1)

```python
(sp-torch2) fang@fang:/home/cmr/LHH/SNN_Attention_VGG$ python3 CIFAR10_VGG.py --T 1 --model spiking_vgg7 --data-path /home/cmr/LHH/SNN_Attention_VGG/CIFAR10 --batch-size 64 --lr 0.001 --lr-scheduler cosa --epochs 200 --lr-warmup-epochs 0 --opt adamw --train-crop-size 32 --val-crop-size 32 --val-resize-size 32 --cupy --device cuda:1
Not using distributed mode
Namespace(data_path='/home/cmr/LHH/SNN_Attention_VGG/CIFAR10', model='spiking_vgg7', device='cuda:1', batch_size=64, epochs=200, workers=16, opt='adamw', lr=0.001, momentum=0.9, weight_decay=0.0, norm_weight_decay=None, label_smoothing=0.1, mixup_alpha=0.2, cutmix_alpha=1.0, lr_scheduler='cosa', lr_warmup_epochs=0, lr_warmup_method='linear', lr_warmup_decay=0.01, lr_step_size=30, lr_gamma=0.1, output_dir='./logs', resume=None, start_epoch=0, cache_dataset=False, auto_augment='ta_wide', random_erase=0.1, sync_bn=False, test_only=False, pretrained=False, world_size=1, dist_url='env://', model_ema=False, model_ema_steps=32, model_ema_decay=0.99998, interpolation='bilinear', val_resize_size=32, val_crop_size=32, train_crop_size=32, clip_grad_norm=None, ra_sampler=False, ra_reps=4, prototype=False, weights=None, seed=2023, print_logdir=False, clean=False, disable_pinmemory=False, disable_amp=False, local_rank=None, disable_uda=False, resume_path='./resume', T=1, cupy=True, distributed=False)
Loading data
Loading training data
Files already downloaded and verified
Took 1.151763916015625
Loading validation data
Files already downloaded and verified
Creating data loaders
Creating model
SpikingVGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), step_mode=m)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, step_mode=m)
    (2): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=m, backend=cupy, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), step_mode=m)
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, step_mode=m)
    (5): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=m, backend=cupy, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False, step_mode=m)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), step_mode=m)
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, step_mode=m)
    (9): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=m, backend=cupy, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), step_mode=m)
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, step_mode=m)
    (12): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=m, backend=cupy, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (13): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), step_mode=m)
    (14): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True, step_mode=m)
    (15): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=m, backend=cupy, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(8, 8), step_mode=m)
  (classifier): Sequential(
    (0): Linear(in_features=32768, out_features=1024, bias=True)
    (1): LIFNode(
      v_threshold=1.0, v_reset=0.0, detach_reset=True, step_mode=m, backend=cupy, tau=2.0
      (surrogate_function): ATan(alpha=2.0, spiking=True)
    )
    (2): Dropout(p=0.5)
    (3): Linear(in_features=1024, out_features=10, bias=True)
  )
)
Traceback (most recent call last):
  File "/home/cmr/LHH/SNN_Attention_VGG/CIFAR10_VGG.py", line 49, in <module>
    print(trainer.main_firing_rate(args))
  File "/home/cmr/LHH/SNN_Attention_VGG/spikingjelly/activation_based/model/train_classify.py", line 864, in main_firing_rate
    train_loss, train_acc1, train_acc5 = self.train_one_epoch(model, criterion, optimizer, data_loader,
  File "/home/cmr/LHH/SNN_Attention_VGG/spikingjelly/activation_based/model/train_classify.py", line 83, in train_one_epoch
    output = self.process_model_output(args, model(image))      # 脉冲发放频率
  File "/home/fang/anaconda3/envs/sp-torch2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cmr/LHH/SNN_Attention_VGG/spikingjelly/activation_based/model/spiking_vgg.py", line 57, in forward
    x = self.classifier(x)
  File "/home/fang/anaconda3/envs/sp-torch2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fang/anaconda3/envs/sp-torch2/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/fang/anaconda3/envs/sp-torch2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fang/anaconda3/envs/sp-torch2/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x8192 and 32768x1024)

# ...
```

**Comment by ridgerchu** [comment]
你好，非常抱歉没有及时回复，这个包目前已经过时了，请最好使用目前版本的Spikingjelly中的Attention机制并结合目前版本中的VGG网络实现相同的功能，效果将会更好。且MA-SNN论文中采用的是ResNet网络，本repo仅是MA-SNN中的VGG尝试。请您移步目前版本的spikingjelly中的Attention机制：
https://github.com/fangwei123456/spikingjelly/blob/master/spikingjelly/activation_based/layer.py#L2016

**Comment by QianpengLi577** [comment]
Modify  `cfg` in spiking_vgg.py
`'F' : [64, 64, 'M', 128, 256, 512]` works well @li17855320680
